import os,sys
fspeak = open('speak','w')
fspeak.write("Ciao ! Io sono Kurti, un cervello digitale creato da Fabio Internicola, e posso svolgere moltissime funzioni.")
fspeak.close()
os.system('start speak.exe')
print("Hello ! I'm Kurti, a digital mind created by Fabio Internicola, and I'm able to do a lot of thing.\n")
print("If you want I can do a calculation, or I can send an E-Mail. You just have to type the command corresponding to the action you want me to do !\n")
os.system('pause')
os.system('cls')
print('Kurti\n____________________________________________________________________________\n')
print("Setup.\n")
fspeak = open('speak','w')
fspeak.write('Benvenuto, Come ti chiami ?')
fspeak.close()
os.system('start speak.exe')
name = input("What's your name ?\n")
fname = open('name','w')
fname.write(name)
fname.close()
fspeak = open('speak','w')
fspeak.write("Qual'è il tuo colore prferito ?")
fspeak.close()
os.system('start speak.exe')
print("Watch to this:\n")
print("1 = Blue\n2 = Green\n4 = Bordeaux\n5 = Violet\n8 = Grey\nb = White Blue\nc = Red\ne = Yellow\nf = White")
color = input("What's your favourite color ?\n")
os.system("color %s" % color)
fcolor = open("color","w")
fcolor.write(color)
fcolor.close()
fspeak = open('speak','w')
fspeak.write('')
fspeak.close()
os.system('pause')
os.system('start main.py')
